### ISSUE TITLE
服务报错

### ISSUE THREAD

**Issue by lliule** [ng-nice/code-book-forum#5]
我使用 fj create BookForum ,然后fj server。访问的主页，但是访问不了其他页面，包括NoFound页面。
还有我生成的module是 app,并不是com.ngnice.app.

angular.js:78 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:nomod] Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.32/$injector/nomod?p0=app
    at http://localhost:5000/bower_components/angular/angular.js:78:12
    at http://localhost:5000/bower_components/angular/angular.js:1679:17
    at ensure (http://localhost:5000/bower_components/angular/angular.js:1603:38)
    at module (http://localhost:5000/bower_components/angular/angular.js:1677:14)
    at http://localhost:5000/bower_components/angular/angular.js:3879:22
    at forEach (http://localhost:5000/bower_components/angular/angular.js:325:18)
    at loadModules (http://localhost:5000/bower_components/angular/angular.js:3873:5)
    at createInjector (http://localhost:5000/bower_components/angular/angular.js:3813:11)
    at doBootstrap (http://localhost:5000/bower_components/angular/angular.js:1446:20)
    at bootstrap (http://localhost:5000/bower_components/angular/angular.js:1461:12)
http://errors.angularjs.org/1.2.32/$injector/modulerr?p0=app&p1=Error%3A%20…F%2Flocalhost%3A5000%2Fbower_components%2Fangular%2Fangular.js%3A1461%3A12)
    at http://localhost:5000/bower_components/angular/angular.js:78:12
    at http://localhost:5000/bower_components/angular/angular.js:1679:17
    at ensure (http://localhost:5000/bower_components/angular/angular.js:1603:38)
    at module (http://localhost:5000/bower_components/angular/angular.js:1677:14)
    at http://localhost:5000/bower_components/angular/angular.js:3879:22
    at forEach (http://localhost:5000/bower_components/angular/angular.js:325:18)
    at loadModules (http://localhost:5000/bower_components/angular/angular.js:3873:5)
    at createInjector (http://localhost:5000/bower_components/angular/angular.js:3813:11)
    at doBootstrap (http://localhost:5000/bower_components/angular/angular.js:1446:20)
    at bootstrap (http://localhost:5000/bower_components/angular/angular.js:1461:12)
http://errors.angularjs.org/1.2.32/$injector/modulerr?p0=app&p1=Error%3A%20…F%2Flocalhost%3A5000%2Fbower_components%2Fangular%2Fangular.js%3A1461%3A12)
    at http://localhost:5000/bower_components/angular/angular.js:78:12
    at http://localhost:5000/bower_components/angular/angular.js:3907:15
    at forEach (http://localhost:5000/bower_components/angular/angular.js:325:18)
    at loadModules (http://localhost:5000/bower_components/angular/angular.js:3873:5)
    at createInjector (http://localhost:5000/bower_components/angular/angular.js:3813:11)
    at doBootstrap (http://localhost:5000/bower_components/angular/angular.js:1446:20)
    at bootstrap (http://localhost:5000/bower_components/angular/angular.js:1461:12)
    at angularInit (http://localhost:5000/bower_components/angular/angular.js:1370:5)
    at HTMLDocument.<anonymous> (http://localhost:5000/bower_components/angular/angular.js:22192:5)
    at fire (http://localhost:5000/bower_components/jquery/dist/jquery.js:3148:30)

**Comment by zhuoNy** [comment]
http://localhost:5000/#/reader/create

注意 # 号
